function ApplyJSToTable(tableid){var table=$("#"+tableid+"");$.extend(true,$.fn.DataTable.TableTools.classes,{"container":"btn-group tabletools-dropdown-on-portlet","buttons":{"normal":"btn btn-sm default","disabled":"btn btn-sm default disabled"},"collection":{"container":"DTTT_dropdown dropdown-menu tabletools-dropdown-menu"}});$("#"+tableid+"").dataTable().fnDestroy();$("#"+tableid+"").dataTable({"language":{"aria":{"sortAscending":": activate to sort column ascending","sortDescending":": activate to sort column descending"},"emptyTable":"No data available in table","infoEmpty":"No entries found","infoFiltered":"(filtered _TOTAL_ from _MAX_ total entries)","lengthMenu":"Show _MENU_ entries","search":"Search","zeroRecords":"No matching records found"},"bLengthChange":false,"paging":false,"bSort":true,"info":false,"infoFiltered":true,"aaSorting":[],"language":{"search":"Search: "},"columnDefs":[{'orderable':false,'targets':['nosort','nosortsearch']},{"searchable":false,"targets":['nosearch','nosortsearch']}]})}
function initpumistablescroll(tableid){var table=$("#"+tableid+"");$("#"+tableid+"").dataTable().fnDestroy();var oTable=table.dataTable({"dom":"<'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r>t<'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>","scrollY":"300","deferRender":true,"bPaginate":false,"info":false,"lengthMenu":[[5,15,20,-1],[5,15,20,"All"]],"pageLength":10,"columnDefs":[{'orderable':false,'targets':['nosort','nosortsearch']},{"searchable":false,"targets":['nosearch','nosortsearch']}]});}
function initpumistablescroll_500(tableid){var table=$("#"+tableid+"");$("#"+tableid+"").dataTable().fnDestroy();var oTable=table.dataTable({"dom":"<'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r>t<'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>","scrollY":"500","deferRender":true,"bPaginate":false,"info":false,"lengthMenu":[[5,15,20,-1],[5,15,20,"All"]],"pageLength":10,"columnDefs":[{'orderable':false,'targets':['nosort','nosortsearch']},{"searchable":false,"targets":['nosearch','nosortsearch']}]});}
function initDTransporttablescroll(tableid){var table=$("#"+tableid+"");$("#"+tableid+"").dataTable().fnDestroy();var oTable=table.dataTable({"dom":"<'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r>t<'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>","scrollY":"350","deferRender":true,"bLengthChange":false,"info":false,"bPaginate":false,"order":[],"columnDefs":[{'orderable':false,'targets':['nosort','nosortsearch']},{"searchable":false,"targets":['nosearch','nosortsearch']}]});}
function CheckAll(){var $allCheckbox=$('.allCheckbox :checkbox');var $checkboxes=$('.singleCheckbox :checkbox');if($allCheckbox.is(':checked')){$checkboxes.attr('checked','checked');$checkboxes.parent().addClass('checked');}
else{$checkboxes.removeAttr('checked');$checkboxes.parent().removeClass('checked');}}
function CheckAll2(){var $allCheckbox=$('.allCheckbox2 :checkbox');var $checkboxes=$('.singleCheckbox2 :checkbox');if($allCheckbox.is(':checked')){$checkboxes.attr('checked','checked');$checkboxes.parent().addClass('checked');}
else{$checkboxes.removeAttr('checked');$checkboxes.parent().removeClass('checked');}}
function CheckAll3(){var $allCheckbox=$('.allCheckbox3 :checkbox');var $checkboxes=$('.singleCheckbox3 :checkbox');if($allCheckbox.is(':checked')){$checkboxes.attr('checked','checked');$checkboxes.parent().addClass('checked');}
else{$checkboxes.removeAttr('checked');$checkboxes.parent().removeClass('checked');}}
$('.date-picker-nofuture').datepicker({startDate:"01-01-1900",endDate:"new date()",autoclose:true,todayHighlight:true});$('.date-picker-nopastdate').datepicker({startDate:"new date()",autoclose:true,todayHighlight:true});$('.date-picker').datepicker({startDate:"01-01-1900",autoclose:true,todayHighlight:true});$('.date-picker-minDate1900').datepicker({startDate:"01-01-1900",endDate:"new date()",autoclose:true,todayHighlight:true});