var Layout=function(){var layoutImgPath='admin/layout3/img/';var layoutCssPath='admin/layout3/css/';var resBreakpointMd=Metronic.getResponsiveBreakpoint('md');var handleHeader=function(){$('.page-header').on('click','.search-form',function(e){$(this).addClass("open");$(this).find('.form-control').focus();$('.page-header .search-form .form-control').on('blur',function(e){$(this).closest('.search-form').removeClass("open");$(this).unbind("blur");});});$('.page-header').on('keypress','.hor-menu .search-form .form-control',function(e){if(e.which==13){$(this).closest('.search-form').submit();return false;}});$('.page-header').on('mousedown','.search-form.open .submit',function(e){e.preventDefault();e.stopPropagation();$(this).closest('.search-form').submit();});$('body').on('click','.page-header-top-fixed .page-header-top .menu-toggler',function(){Metronic.scrollTop();});};
var handleMainMenu=function(){$(".page-header .menu-toggler").on("click",function(event){if(Metronic.getViewPort().width<resBreakpointMd){var menu=$(".page-header .page-header-menu");if(menu.is(":visible")){menu.slideUp(300);}else{menu.slideDown(300);}
if($('body').hasClass('page-header-top-fixed')){Metronic.scrollTop();}}});$(".hor-menu .dropdown-submenu > a").on("click",function(e){if(Metronic.getViewPort().width<resBreakpointMd){if($(this).next().hasClass('dropdown-menu')){e.stopPropagation();if($(this).parent().hasClass("open")){$(this).parent().removeClass("open");$(this).next().hide();}else{$(this).parent().addClass("open");$(this).next().show();}}}});if(Metronic.getViewPort().width>=resBreakpointMd){$('.hor-menu [data-hover="megamenu-dropdown"]').not('.hover-initialized').each(function(){$(this).dropdownHover();$(this).addClass('hover-initialized');});}
$(document).on('click','.hor-menu .menu-dropdown > a[data-hover="megamenu-dropdown"]',function(){if(Metronic.getViewPort().width<resBreakpointMd){Metronic.scrollTo($(this));}});$(document).on('click','.mega-menu-dropdown .dropdown-menu, .classic-menu-dropdown .dropdown-menu',function(e){e.stopPropagation();});$(window).scroll(function(){var offset=75;if($('body').hasClass('page-header-menu-fixed')){if($(window).scrollTop()>offset){$(".page-header-menu").addClass("fixed");}else{$(".page-header-menu").removeClass("fixed");}}
if($('body').hasClass('page-header-top-fixed')){if($(window).scrollTop()>offset){$(".page-header-top").addClass("fixed");}else{$(".page-header-top").removeClass("fixed");}}});};var handleMainMenuActiveLink=function(mode,el){var url=location.hash.toLowerCase();var menu=$('.hor-menu');if(mode==='click'||mode==='set'){el=$(el);}else if(mode==='match'){menu.find("li > a").each(function(){var path=$(this).attr("href").toLowerCase();if(path.length>1&&url.substr(1,path.length-1)==path.substr(1)){el=$(this);return;}});}
if(!el||el.size()==0){return;}
if(el.attr('href').toLowerCase()==='javascript:;'||el.attr('href').toLowerCase()==='#'){return;}
menu.find('li.active').removeClass('active');menu.find('li > a > .selected').remove();menu.find('li.open').removeClass('open');el.parents('li').each(function(){$(this).addClass('active');if($(this).parent('ul.navbar-nav').size()===1){$(this).find('> a').append('<span class="selected"></span>');}});};var handleMainMenuOnResize=function(){var width=Metronic.getViewPort().width;var menu=$(".page-header-menu");if(width>=resBreakpointMd&&menu.data('breakpoint')!=='desktop'){$('.hor-menu [data-toggle="dropdown"].active').removeClass('open');menu.data('breakpoint','desktop');$('.hor-menu [data-hover="megamenu-dropdown"]').not('.hover-initialized').each(function(){$(this).dropdownHover();$(this).addClass('hover-initialized');});$('.hor-menu .navbar-nav li.open').removeClass('open');$(".page-header-menu").css("display","block");}else if(width<resBreakpointMd&&menu.data('breakpoint')!=='mobile'){$('.hor-menu [data-toggle="dropdown"].active').addClass('open');menu.data('breakpoint','mobile');$('.hor-menu [data-hover="megamenu-dropdown"].hover-initialized').each(function(){$(this).unbind('hover');$(this).parent().unbind('hover').find('.dropdown-submenu').each(function(){$(this).unbind('hover');});$(this).removeClass('hover-initialized');});}else if(width<resBreakpointMd){}};var handleContentHeight=function(){var height;if($('body').height()<Metronic.getViewPort().height){height=Metronic.getViewPort().height-
$('.page-header').outerHeight()-
($('.page-container').outerHeight()-$('.page-content').outerHeight())-
$('.page-prefooter').outerHeight()-
$('.page-footer').outerHeight();$('.page-content').css('min-height',height);}};var handleGoTop=function(){var offset=100;var duration=500;if(navigator.userAgent.match(/iPhone|iPad|iPod/i)){$(window).bind("touchend touchcancel touchleave",function(e){if($(this).scrollTop()>offset){$('.scroll-to-top').fadeIn(duration);}else{$('.scroll-to-top').fadeOut(duration);}});}else{$(window).scroll(function(){if($(this).scrollTop()>offset){$('.scroll-to-top').fadeIn(duration);}else{$('.scroll-to-top').fadeOut(duration);}});}
$('.scroll-to-top').click(function(e){e.preventDefault();$('html, body').animate({scrollTop:0},duration);return false;});};return{initHeader:function(){handleHeader();handleMainMenu();Metronic.addResizeHandler(handleMainMenuOnResize);if(Metronic.isAngularJsApp()){handleMainMenuActiveLink('match');}},initContent:function(){handleContentHeight();},initFooter:function(){handleGoTop();},init:function(){this.initHeader();this.initContent();this.initFooter();},setMainMenuActiveLink:function(mode,el){handleMainMenuActiveLink(mode,el);},closeMainMenu:function(){$('.hor-menu').find('li.open').removeClass('open');if(Metronic.getViewPort().width<resBreakpointMd&&$('.page-header-menu').is(":visible")){$('.page-header .menu-toggler').click();}},getLayoutImgPath:function(){return Metronic.getAssetsPath()+layoutImgPath;},getLayoutCssPath:function(){return Metronic.getAssetsPath()+layoutCssPath;}};}();